### ISSUE TITLE
Raise Python minimum to 3.7 for OIIO 3.0

### ISSUE THREAD

**Issue by lgritz** [AcademySoftwareFoundation/OpenImageIO#4157]
```[tasklist]
### Tasks
- [ ] INSTALL.md -- document the change
- [ ] Any simplifications in python/*.{h,cpp}
- [ ] ci.yml -- eliminate test cases that use python 2.7 (or change them to use 3.x)
- [ ] Look through all our python scripts, simplify places where we have python2 specific things (such as still having `from __future__ import print_function`)
```

**Comment by lgritz** [comment]
Was fixed by #4200
